name: Container release

on:
  push:
    tags:
      - "v*.*.*"

concurrency:
  group: container-release-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  attestations: write
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    uses: berntpopp/genefoundry-router/.github/workflows/_container-release.yml@35f31f3a53fd423ca4f88f4d10e13d4f23011b7a
